### PR TITLE
0.2.0 making 2 identity properties optional - DO NOT MERGE

### PR DESCRIPTION
**Pull request by nickvelloff**
Passport response for add identity does not return `id` and `description`. 

I suspect this is a Passport bug, but created this just so I could continue. I suspect you'll discard this ultimately.

### CODE REVIEW

**Comment by paulyoung** [comment]
These were present when I added the method or I would have brought that up then.

The fact that I was receiving this (at least for one provider) and you're not does sound like a bug. The fact that ID is missing at all isn't good.

**Comment by paulyoung** [comment]
@trustmaster can you offer any insight?

**Comment by paulyoung** [comment]
@nickvelloff can you confirm which provider you were seeing this with. So far this is what I know:

* **Facebook**: expected response
* **Google**: unexpected response

**Comment by paulyoung** [comment]
It's possible that when I tested Facebook that identity was added but decoding the response was failing and I didn't realize.

@trustmaster – in any case, could we follow typical REST semantics here and have the resource be returned from a `POST`?

**Comment by nickvelloff** [comment]
It could be easily overlooked if you were just testing for a `Result`

**Comment by nickvelloff** [comment]
To confirm it is only Facebook I  have tested, as I was delayed figuring this out a bit.

**Comment by paulyoung** [comment]
The tests only return the provided fixture and don't normally make any network requests, so wouldn't know if the actual server response was different or had changed.

When I was testing before I replaced the dummy token and parameters with real ones and saw that the my Facebook identity was added as a result.

I _think_ at this point the `Identity` was also properly decoded and the test failed because it was not the same as the expected identity, but not because decoding failed and it was `nil`.

**Comment by paulyoung** [comment]
Closing this in light of recent news that the API response is going to be updated.

Feel free to continue any discussion here though :+1:

**Comment by trustmaster** [comment]
API response updated.

**Comment by nickvelloff** [comment]
@trustmaster thanks!

**Pull request closed without merging**
